backend:
  name: github
  repo: nokotaro/zola-portfolio
  branch: main
  cms_label_prefix: netlify-cms/
  site_domain: nokotaro.com

locale: "ja"
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "Blog"
    label: "ブログ"
    folder: "content/blog"
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日時", name: "date", widget: "datetime" }
      - { label: "説明", name: "description", widget: "string" }
      - label: "分類"
        name: "taxonomies"
        widget: "object"
        fields:
          - { label: "ラベル", name: "tags", widget: "list", required: false }
      - label: "詳細"
        name: "extra"
        widget: "object"
        fields:
          - { label: "お気に入り", name: "featured", widget: "boolean", required: false }
          - { label: "リンク", name: "link", widget: "string" }
          - { label: "画像", name: image, widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "Projects"
    label: "プロジェクト"
    folder: "content/projects"
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日時", name: "date", widget: "datetime" }
      - { label: "説明", name: "description", widget: "string" }
      - label: "分類"
        name: "taxonomies"
        widget: "object"
        fields:
          - { label: "ラベル", name: "tags", widget: "list", required: false }
      - label: "詳細"
        name: "extra"
        widget: "object"
        fields:
          - { label: "お気に入り", name: "featured", widget: "boolean", required: false }
          - { label: "リンク", name: "link", widget: "string" }
          - { label: "画像", name: image, widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "Contributions"
    label: "OSS"
    folder: "content/opensource"
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日時", name: "date", widget: "datetime" }
      - { label: "説明", name: "description", widget: "string" }
      - label: "分類"
        name: "taxonomies"
        widget: "object"
        fields:
          - { label: "ラベル", name: "tags", widget: "list", required: false }
      - label: "詳細"
        name: "extra"
        widget: "object"
        fields:
          - { label: "お気に入り", name: "featured", widget: "boolean", required: false }
          - { label: "リンク", name: "link", widget: "string" }
          - { label: "画像", name: image, widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "Publications"
    label: "出版物"
    folder: "content/publications"
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日時", name: "date", widget: "datetime" }
      - { label: "説明", name: "description", widget: "string" }
      - label: "分類"
        name: "taxonomies"
        widget: "object"
        fields:
          - { label: "ラベル", name: "tags", widget: "list", required: false }
      - label: "詳細"
        name: "extra"
        widget: "object"
        fields:
          - { label: "お気に入り", name: "featured", widget: "boolean", required: false }
          - { label: "引用", name: "bibtex", widget: "file" }
          - { label: "リンク", name: "link", widget: "string" }
          - { label: "画像", name: image, widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "settings"
    label: "設定"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "設定"
        file: "config.toml"
        extension: toml
        description: "サイト設定"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - name: "extra"
            label: "パラメータ"
            widget: "object"
            fields:
              - { label: "名字", name: "first_name", widget: "string" }
              - { label: "名前", name: "last_name", widget: "string" }
              - { label: "住所", name: "address", widget: "string" }
              - { label: "アイコン", name: "avatar", widget: "image" }
              - { label: "ファビコン", name: "favicon", widget: "image" }
              - { label: "メールアドレス", name: "email", widget: "string" }
              - { label: "電話番号", name: "phone", widget: "string" }
              - {
                  label: "数式",
                  name: "katex",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_about",
                  name: "show_about",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_skills",
                  name: "show_skills",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_projects",
                  name: "show_projects",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_opensource",
                  name: "show_opensource",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_publications",
                  name: "show_publications",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_experience",
                  name: "show_experience",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_education",
                  name: "show_education",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "show_blog",
                  name: "show_blog",
                  widget: "boolean",
                  required: false,
                }